# Generated by Django 4.2.6 on 2023-10-18 20:58

from django.db import migrations, models

# Crea una nueva tabla en la base de datos llamada "Todo"

# En general aquí se hace la migración inicial de la base de datos,
# con código generado por django,
# que crea la estructura de la tabla "Todo" con las columnas
# mencionadas. Las migraciones en Django se utilizan para
# mantener la consistencia entre el modelo de datos de la
# aplicación y la estructura de la base de datos a lo largo del
# tiempo.


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=130)),
                ("description", models.CharField(max_length=130)),
                ("done", models.BooleanField(default=False)),
            ],
        ),
    ]
